### ISSUE TITLE
can not complie ....

### ISSUE THREAD

**Issue by wony-zheng** [winshining/nginx-http-flv-module#21]
can not compile with nginx, with release 1.2.2.
the nginx version : 1.12.2
```bash
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/src/nginx-http-flv-module-1.2.2 -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
        -o objs/addon/nginx-http-flv-module-1.2.2/ngx_rtmp_live_module.o \
        /usr/src/nginx-http-flv-module-1.2.2/ngx_rtmp_live_module.c
/usr/src/nginx-http-flv-module-1.2.2/ngx_rtmp_live_module.c: In function 'ngx_rtmp_live_data':
/usr/src/nginx-http-flv-module-1.2.2/ngx_rtmp_live_module.c:1191:37: error: variable 'msg_type' set but not used [-Werror=unused-but-set-variable]
     u_char                         *msg_type;
                                     ^~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by wony-zheng** [comment]
oh, it is fixed in master, close it
